config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#top'
  get 'top', to: 'pages#top'
  post 'search_by_zipcode', to: 'pages#search_by_zipcode'
  post 'search_by_address', to: 'pages#search_by_address'
  get 'search_by_zipcode', to: redirect('/top')
  get 'search_by_address', to: redirect('/top')
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :postal_code

  scope :zip_code_like, -> (zip_code) { where('zipcode LIKE ?', "%#{zip_code}%") if zip_code.present? }
  scope :prefecture_like, -> (prefecture) { where(prefecture: prefecture) if prefecture.present? }
  scope :city_like, -> (city) { where('city LIKE ?', "%#{city}%") if city.present? }
  scope :street_like, -> (street) { where('street LIKE ?', "%#{street}%") if street.present? }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/postal_code.rb
class PostalCode < ApplicationRecord
  has_one :address
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_prefectures
  before_action :set_by_zipcode, only: [:search_by_zipcode]
  before_action :set_by_address, only: [:search_by_address]

  def top
  end

  def search_by_zipcode
    render :top
  end

  def search_by_address
    render :top
  end

  private

  def set_by_zipcode
    @addresses = if params[:zip_code].blank?
                   nil
                 else
                   Address.zip_code_like(params[:zip_code])
                 end
    @zip_code = params[:zip_code]
  end

  def set_by_address
    @addresses = if params[:prefecture].blank? && params[:city].blank? && params[:street].blank?
                   nil
                 else
                   Address.prefecture_like(params[:prefecture]).city_like(params[:city]).street_like(params[:street])
                 end
    @selected_prefecture = params[:prefecture]
    @city = params[:city]
    @street = params[:street]
  end

  def set_prefectures
    @prefectures = Address.pluck(:prefecture).uniq!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZipCode</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/top.html.slim
h1 住所検索

.box
  h3 From Zipcode
  = form_tag(search_by_zipcode_path, method: :post) do
    = number_field_tag :zip_code, @zip_code, :maxlength => 7
    = submit_tag "検索"

  h3 From Address
  = form_tag(search_by_address_path, method: :post) do
    = select_tag :prefecture, options_for_select(@prefectures, :selected => @selected_prefecture), :include_blank => true
    = text_field_tag :city, @city
    = text_field_tag :street, @street
    = submit_tag "検索"

  table
    thead
      tr
        th 郵便番号
        th 都道府県
        th 市区町村
        th 町名
    tbody
    - if @addresses.present?
      - @addresses.each do |address|
        tr
          td = address.zipcode
          td = address.prefecture
          td = address.city
          td = address.street